seven = input('Introduce el numero 7: ')
four = input('Introduce el numero 4: ')
print('7 + 4 = ', int(seven) + int(four))
print('7 - 4 = ', int(seven) - int(four))
print('7 * 4 = ', int(seven) * int(four))
print('7 / 4 = ', int(seven) / int(four))
